Document: fixpr12icons
Title: Debian fixpr12icons Manual
Author: <insert document author here>
Abstract: This manual describes what fixpr12icons is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fixpr12icons/fixpr12icons.sgml.gz

Format: postscript
Files: /usr/share/doc/fixpr12icons/fixpr12icons.ps.gz

Format: text
Files: /usr/share/doc/fixpr12icons/fixpr12icons.text.gz

Format: HTML
Index: /usr/share/doc/fixpr12icons/html/index.html
Files: /usr/share/doc/fixpr12icons/html/*.html
